### ISSUE TITLE
2 vips with same ip address and different port number (when trying to deploy)

### ISSUE THREAD

**Issue by Niklaus-xie** [F5Networks/f5-adcaas-openstack#190]
seems to me this is now blocked because it first tries to allocate the vip ip addr from neutron; and
it would complain that this ip addr is already been allocated.

**Comment by olvandeng** [comment]
JIRA Bug 1522 for this issue.

**Comment by zongzw** [comment]
https://github.com/F5Networks/f5-adcaas-openstack/pull/230, fixed.
